pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - docs/**
      - README.md

pool:
  name: 'Default'

steps:
- task: Checkout@1
  displayName: 'Checkout repository'

# Sprawdzanie zawartości config.json (opcjonalne)
- script: |
    echo "Displaying config.json:"
    cat config.json
  displayName: 'Display existing config.json'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(dockerImageName):$(dockerImageTag)
      $(dockerImageName):latest

- script: |
    docker save $(dockerImageName):$(dockerImageTag) -o ibda-tests.tar
  displayName: 'Save Docker Image as TAR'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'ibda-tests.tar'
    artifact: 'docker-image'
  displayName: 'Publish Docker Image as Artifact'
