# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build image
    pool:
      name: Default

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'ibda-at'
        tags: |
          $(tag)

    # Save Docker image as TAR file
    - script: |
        docker save -o $(Build.ArtifactStagingDirectory)/image-$(tag).tar ibda-at:$(tag)
      displayName: Save Docker image as TAR

    # Publish TAR file as artifact
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'image-$(tag).tar'
