pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - docs/**
      - README.md

pool:
  name: 'Default'

steps:
# 1. Sprawdzenie repozytorium
- task: Checkout@1
  displayName: 'Checkout repository'

# 2. Debugowanie środowiska (opcjonalne)
- script: |
    echo "Environment variables:"
    printenv
  displayName: 'Print all environment variables'

# 3. Budowa obrazu Dockera
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(dockerImageName):$(dockerImageTag)
      $(dockerImageName):latest

# 4. Push obrazu Dockera do GitHub Container Registry (lub innego rejestru)
- task: Docker@2
  displayName: 'Push Docker Image to GitHub Container Registry'
  inputs:
    command: 'push'
    repository: '$(dockerImageName)'
    tags: |
      $(dockerImageName):$(dockerImageTag)
      $(dockerImageName):latest