pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - docs/**
      - README.md

#macos-latest
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@1
  displayName: 'Checkout repository'

- script: |
    echo "TEST_OPERATORIBDA_PASSWORD=$(TEST_OPERATORIBDA_PASSWORD)"
    echo "TEST_KIEROWNIKLAB_PASSWORD=$(TEST_KIEROWNIKLAB_PASSWORD)"
  displayName: 'Debugging environment variables'


- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(dockerImageName):$(dockerImageTag)
      $(dockerImageName):latest

- script: |
    docker save $(dockerImageName):$(dockerImageTag) -o ibda-tests.tar
  displayName: 'Save Docker Image as TAR'
#dbug
- script: |
    echo "TEST_OPERATORIBDA_PASSWORD=$(TEST_OPERATORIBDA_PASSWORD)"
  displayName: 'Debug credentials'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'ibda-tests.tar'
    artifact: 'docker-image'
  displayName: 'Publish Docker Image as Artifact'   