pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - docs/**
      - README.md

#macos-latest
pool:
  vmImage: 'Azure Pipelines'

variables:
- name:  dockerImageName
  value: 'ibda-tests'
- name:  dockerImageTag
  value: '123'


steps:
- task: Checkout@1
  displayName: 'Checkout repository'

- script: |
    echo "TEST_OPERATORIBDA_PASSWORD=$(TEST_OPERATORIBDA_PASSWORD)"
    echo "TEST_KIEROWNIKLAB_PASSWORD=$(TEST_KIEROWNIKLAB_PASSWORD)"
  displayName: 'Debugging environment variables'

- script: |
    cat > config.json <<EOF
    {
      "test_operatorIBDA": {
        "username": "test_operatorIBDA",
        "password": "$(TEST_OPERATORIBDA_PASSWORD)"
      },
      "test_kierownikLAB": {
        "username": "test_kierownikLAB",
        "password": "$(TEST_KIEROWNIKLAB_PASSWORD)"
      },
      "test_OpiekunIBDA": {
        "username": "test_OpiekunIBDA",
        "password": "$(TEST_OPIEKUNIBDA_PASSWORD)"
      },
      "test_PracownikBWG": {
        "username": "test_PracownikBWG",
        "password": "$(TEST_PRACOWNIKBWG_PASSWORD)"
      },
      "test_PracownikSAP": {
        "username": "test_PracownikSAP",
        "password": "$(TEST_PRACOWNIKSAP_PASSWORD)"
      },
      "test_PracownikCBIBDA": {
        "username": "test_PracownikCBIBDA",
        "password": "$(TEST_PRACOWNIKCBIBDA_PASSWORD)"
      },
      "test_koordynatorWydz": {
        "username": "test_koordynatorWydz",
        "password": "$(TEST_KOORDYNATORWYDZ_PASSWORD)"
      },
      "test_KierownikDP": {
        "username": "test_KierownikDP",
        "password": "$(TEST_KIEROWNIKDP_PASSWORD)"
      }
    }
    EOF
  displayName: 'Generate config.json with credentials'


- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(dockerImageName):$(dockerImageTag)
      $(dockerImageName):latest

- script: |
    docker save $(dockerImageName):$(dockerImageTag) -o ibda-tests.tar
  displayName: 'Save Docker Image as TAR'
#dbug
- script: |
    echo "TEST_OPERATORIBDA_PASSWORD=$(TEST_OPERATORIBDA_PASSWORD)"
  displayName: 'Debug credentials'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'ibda-tests.tar'
    artifact: 'docker-image'
  displayName: 'Publish Docker Image as Artifact'   