trigger: none 
pool:
  name: US_ING  

jobs:
- job: GPU_Benchmark
  displayName: "Check NVIDIA GPU"
  steps:
  - script: |
      docker run --rm --gpus all nvidia/cuda:11.8.0-base-ubuntu22.04 nvidia-smi
    displayName: "Run nvidia-smi in Docker"